---

language: go

go:
  - '1.13.x'

install:
  - pip install cram --user

before_script:
  - go vet -v ./...

script:
  - GOOS=linux GOARCH=amd64 go build -o certigo-linux-amd64
  - GOOS=darwin GOARCH=amd64 go build -o certigo-darwin-amd64
  - GOOS=windows GOARCH=amd64 go build -o certigo-windows-amd64.exe
  - go test -v ./...
  - ln -s certigo-linux-amd64 certigo
  - PATH=$PWD:$PATH cram -v tests/*.t

deploy:
  provider: releases
  api_key:
    # mbyczkowski's OAuth token
    secure: SJqQjZ+4TT/CqAPy/7Z/Y1kIoYQt1GMw/kVkh6QpYqTaknqnWmNlwn/GdMATdiFo5X4GsPoE9euc+z5E9FeVgOlxypOzf/H0K2eV5YRitjQYrtzjVCkCnWt6AIOBRHWF31+mtkk2kbG7k0N/cj6GOpj93sX2Bh8+zM3O86SEgC2bipGTuNkR+PJh09Euthe1C/zlELyyo1Hg/rfnD8mRmPK7hSRj0FTlJLCkxHC7ou9r6FMyxC25uRKg7r3bocOOYUyDstZRid5HnKbxhfPhCAE+xHdLuH3+iQdAS0g0TYIfajGEm4nrgCWlMB7hqKcP5Ob3YFNdlmAp/61y2tBRZlk5S3bjU4XnEfjxN7wmAs0Em+SAH9R2U1hl4fDOwxXoBxDuKpu1FH598Q4xA2bfZrnzNnzVXvRTjSAb4a0CzwU8wRuftqCeGWrylaDPRSVVAtTUyukEoV/3KBfZaSCE5xXI7uu2IsqG4SLmxod1X/EdamM16ZkUzrsgtCJGUIjNcOQw1lro9PV1A5oac02hkEwW87N5OY36abTlKhkbpGZJvkN21UF4HUJM/W1UCUMYNZ7hOwU3H2kWZrmWHSXfRvjwJxwqXYVEX4MTULccV8JcPq4fRywV+uCkT/aGEzNXLv++9r7Ut9aqGuQi6Aee2SjtjRBVXeWKpCJMUNB8fow=
  file:
    - certigo-linux-amd64
    - certigo-darwin-amd64
    - certigo-windows-amd64.exe
  skip_cleanup: true
  draft: true
  on:
    repo: square/certigo
    tags: true
