#!/bin/bash -e
# Copyright (C) 2016 Square, Inc.

ORG_PATH="github.com/square"
REPO_PATH="${ORG_PATH}/certigo"

export GOPATH=${PWD}/gopath

rm -f $GOPATH/src/${REPO_PATH}
mkdir -p $GOPATH/src/${ORG_PATH}
ln -s ${PWD} $GOPATH/src/${REPO_PATH}

eval $(go env)

go build -o bin/certigo ${REPO_PATH}

# Generate man page
mkdir -p man
bin/certigo --help-man > man/certigo.1

# Generate completion scripts
mkdir -p shell
bin/certigo --completion-script-zsh > shell/certigo.completion.zsh
bin/certigo --completion-script-bash > shell/certigo.completion.bash
