name: compilecheck.yaml

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Compile Check
    strategy:
      matrix:
        version: ['stable']
        target:
          - {os: 'darwin', platform: 'macos-latest', arch: 'amd64'}
          - {os: 'linux', platform: 'ubuntu-latest', arch: 'amd64'}
          - {os: 'windows', platform: 'windows-latest', arch: 'amd64'}
    runs-on: ${{ matrix.target.platform }}
    permissions:
      contents: write
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # ratchet:actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          check-latest: true
        id: go
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Build binary
        run: |
          go env -w CGO_ENABLED=0
          go build -o certigo .
