---
name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3.0
          install-mode: goinstall
          only-new-issues: true
