---
name: Release

on:
  push:
    tags: ["*"]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        version: ['stable']
        target:
          - {os: 'darwin', platform: 'macos-latest', arch: 'amd64'}
          - {os: 'linux', platform: 'ubuntu-latest', arch: 'amd64'}
          - {os: 'windows', platform: 'windows-latest', arch: 'amd64'}
    runs-on: ${{ matrix.target.platform }}
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # ratchet:actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          check-latest: true
        id: go
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Build binary
        run: go build -o certigo .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4
        with:
          name: certigo-${{ matrix.target.os }}-${{ matrix.target.arch }}
          path: certigo

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Create release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # ratchet:actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release Build (Draft)"
          body: "Release Build (from ${{ github.ref }}/${{ github.sha }})"
          draft: true
          prerelease: true

  add-assets:
    name: Add assets
    runs-on: ubuntu-latest
    needs: [build, release]
    strategy:
      matrix:
        target:
          - {os: 'darwin', arch: 'amd64'}
          - {os: 'linux', arch: 'amd64'}
          - {os: 'windows', arch: 'amd64'}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # ratchet:actions/download-artifact@v4
        with:
          name: certigo-${{ matrix.target.os }}-${{ matrix.target.arch }}
          path: dist
      - name: Upload artifact to release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # ratchet:actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./dist/certigo
          asset_name: certigo-${{ matrix.target.os }}-${{ matrix.target.arch }}
          asset_content_type: application/octet-stream
